### ISSUE TITLE
[Question]How correctly fill the credentials.js file?

### ISSUE THREAD

**Issue by dracorp** [mashery/masherytools#13]
Hello
Every time when I use this tool I get **invalid_client** and:
```
GET /javascripts/jquery-1.12.0.min.js 304 0.315 ms - -
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:516:11)
```
in console.
It is clear what to enter in:
* mashery_user_id/mashery_password
* mashery_area_uuids and name/uuid/tm_hosts/cc_url

But I don't know how to proper fill mashery_api_key/mashery_api_key_secret.
I have a lot of keys and secrets at developer.my_company.com/apps/mykeys. This does not work with any (almost) of the pairs on the given page.

Do I need a special key and secret?

**Comment by rkiesler1** [comment]
Paying customers can obtain a Mashery API v3 key/secret from TIBCO support.

**Comment by dracorp** [comment]
Wow, I didn't expect that. Thank you.

**Comment by rkiesler1** [comment]
You can also register for a key online using https://developer.mashery.com/apps/register

**Comment by dracorp** [comment]
Thank you. I'll try.

**Comment by dracorp** [comment]
After registering an app at developer.mashery.com and after activating the account, everything is fine. Thx.
